### ISSUE TITLE
Cookies not working

### ISSUE THREAD

**Issue by ssakib4040** [Azure-Samples/js-e2e-azure-function-graphql-hello#7]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Any log messages were given by the failure
> context.res.cookie is not a function

### Expected/desired behavior
> Cookie should be set on the browser

### OS and Version?
> Windows 10

### Versions
>Version	10.0.19044 Build 19044

### Mention any other details that might be useful
> I am trying to set cookies from apollo server azure functions but it's not working.

**Comment by ssakib4040** [comment]
This is my code. 
```javascript

import { ApolloServer, gql } from "apollo-server-azure-functions";

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    user: User
  }

  type User {
    id: ID!
    name: String!
    email: String!
  }
`;

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    user: (parents, args, { request, context }, info) => {

      const cookieOptions = {
        httpOnly: true,
        maxAge: 1 * 60 * 60 * 24 * 1000,
        secure: true,
      };
      context.res.cookie("token", "12345", cookieOptions);

      return {
        id: "1",
        name: "John Doe",
        email: "john@example.com",
      };
    },
  },
};

// @ts-ignore
const server = new ApolloServer({
  typeDefs,
  resolvers,
  debug: true,
  context: (context) => {
    return context;
  },
});

export default server.createHandler({
  cors: {
    origin: ["*", "https://studio.apollographql.com"],
    methods: ["GET", "POST", "OPTIONS"],
    allowedHeaders: [
      "access-control-allow-credentials",
      "access-control-allow-origin",
      "content-type",
    ],
  },
});

```
The error 

![Screenshot_1](https://user-images.githubusercontent.com/101496701/198139639-5b944313-dc80-4800-9b4f-f036839aa1cb.png)

**Comment by diberry** [comment]
#in-progress

**Comment by diberry** [comment]
@ssakib4040 Can you try the code.

```
context.res = {
    status: 302, /* Defaults to 200 */
    // body: responseMessage,
    headers: {
        Location: "https://localhost",
    },
    cookies: [
        {
            name: "token",
            value: "mytokenvalue",
            maxAge: 60 * 10,
            // expires: xxx,
            path: "/"
        }
    ]
};
```

Another variation found [here](https://github.com/Azure/azure-functions-host/issues/2737): 

```
context.res = {
    body: "Hello",
    status: 200,
    cookies: [
        {
            name: "cookie1",
            value: "value1"
        },
        {
            name: "cookie2",
            value: "value2",
            maxAge: 60 * 10
        }
    ]
```

**Comment by ssakib4040** [comment]
@diberry Hi, I tried both of the examples & it didn't worked 

**Code**
![Screenshot_1](https://user-images.githubusercontent.com/101496701/199138499-ed42a696-be0f-43c5-8d22-5878e3992e90.png)

**Browser**
![Screenshot_2](https://user-images.githubusercontent.com/101496701/199139017-4b0049dd-1ded-40a0-8412-7aa32f21a7e0.png)

**Postman**
![Screenshot_3](https://user-images.githubusercontent.com/101496701/199139145-91c0093b-8502-4cd1-9f27-0852de675957.png)

**Comment by ssakib4040** [comment]
@diberry [apollo-server-express](https://www.npmjs.com/package/apollo-server-express) is working fine, but it's very expensive to deploy so I am trying [apollo-server-azure-functions](https://www.npmjs.com/package/apollo-server-azure-functions) but it's not working😥
![Screenshot_4](https://user-images.githubusercontent.com/101496701/199140012-6f7d08c7-c1fa-4359-81e2-f3664cbe0868.png)

**Comment by diberry** [comment]
@ssakib4040 ok - let me spend a day or two with this.

**Comment by diberry** [comment]
@ssakib4040 After looking at the issue, the infrastructure, and the [announcement from Apollo for this package](https://github.com/apollographql/apollo-server/issues/6032), I believe Apollo is the correct organization to post this issue because Apollo is providing the server in this sample. It just happens to be running on an Azure Function. Additionally, when I look for a solution on Apollo, it looks like the ApolloServer dependency needs to be swapped out for an Apollo server for express dependency in order to successfully set the cookie. 

None of this is great news. I apologize for this. 

I _believe_ the sample works in this repo without cookes and doesn't currently include cookies in the code. Moving forward with the Apollo dependency, we will re-evaluate its use based on this feedback.
